### ISSUE TITLE
What journal or conference has this paper been included in?

### ISSUE THREAD

**Issue by ZZZ1223** [xinyuaning/MECPformer#1]
This is a wonderful piece of work, and I would like to quote your paper.

**Comment by ChunmengLiu1** [comment]
Thank you for your attention!
please refer:

Liu, C., Li, G., Shen, Y. et al. MECPformer: multi-estimations complementary patch with CNN-transformers for weakly supervised semantic segmentation. Neural Comput & Applic 35, 23249–23264 (2023). https://doi.org/10.1007/s00521-023-08816-2
